[project]
name = "rest-testserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "opencv-python-headless>=4.11.0.86",
]
