repos:
- repo: local
  hooks: 
  - id: fmt
    name: fmt
    description: Format files with cargo fmt.
    entry: cargo fmt
    language: system
    types: [rust]
    args: ["--"]
  - id: clippy
    name: clippy
    description: Lint rust sources
    entry: cargo clippy
    language: system
    args: ["--", "-D", "warnings"]
    types: [rust]
    pass_filenames: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format