[package]
name = "rvimage"
version = "0.1.0"
authors = ["Behrang Shafei"]
edition = "2021"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
egui = "0.16"
egui_wgpu_backend = "0.16"
egui-winit = { version = "0.16", default-features = false, features = ["links"] }
env_logger = "0.9"
log = "0.4"
pixels = "0.9.0"
winit = "0.26"
winit_input_helper = "0.11"
image = "0.24.0"
rfd = "0.7.0"
toml = "0.5.8"
serde = { version="1.0", features = ["derive"] }
lazy_static = "1.4.0"
regex = "1"
walkdir = "2.3.2"
ssh2 = "0.9"
dirs = "4.0.0"
