#!/bin/sh
# generated by ChatGPT
# generate_images.sh

# Generate PNG images displaying numbers using ImageMagick with DejaVu-Sans-Bold font
for i in $(seq 1 5); do
    convert -size 100x100 xc:lightblue -font DejaVu-Sans-Bold -gravity center -pointsize 40 -draw "text 0,0 '$i'" /home/test/image$i.png
done
