pub mod annotations;
mod cache;
pub mod cfg;
pub mod domain;
pub mod file_util;
pub mod history;
pub mod httpserver;
pub mod image_util;
pub mod menu;
mod paths_selector;
mod reader;
pub mod result;
mod ssh;
mod threadpool;
pub mod tools;
pub mod tools_data;
mod types;
pub mod world;

const LEFT_BTN: usize = 0;
const RIGHT_BTN: usize = 1;
