mod cache;
pub mod cfg;
pub mod control;
pub mod domain;
pub mod file_util;
pub mod history;
pub mod httpserver;
mod image_reader;
pub mod image_util;
pub mod menu;
mod paths_selector;
pub mod result;
mod ssh;
mod threadpool;
pub mod tools;
pub mod tools_data;
mod types;
mod util;
pub mod world;
const LEFT_BTN: usize = 0;
const RIGHT_BTN: usize = 1;

pub use tools_data::annotations;
