name: CI
on:
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install reqs
      run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
    - name: Check
      run: cargo check --workspace --all-features
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Fmt
      run: cargo fmt --check
    - name: Run tests
      run: cargo test --verbose

  testing_py_data_models:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Install Dependencies
        working-directory: rvimage-py
        run: uv sync

      - name: Run data model tests
        working-directory: rvimage-py
        run: PYTHONPATH=. uv run pytest test/test.py