name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install reqs
      run: sudo apt-get update && apt-get install -y libgtk-3-dev
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
